// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Jira struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Impact   string `json:"impact"`
	Domain   string `json:"domain"`
	Relnotes string `json:"relnotes"`
}

type Release struct {
	Version     string             `json:"version"`
	FromVer     string             `json:"from_ver"`
	Platform    string             `json:"platform"`
	ReleaseDate string             `json:"release_date"`
	SubmittedBy string             `json:"submitted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ReleaseJira struct {
	ReleaseVersion string `json:"release_version"`
	JiraID         string `json:"jira_id"`
}
