// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: release_jiras.sql

package db

import (
	"context"
)

const getJiraIDsByRelease = `-- name: GetJiraIDsByRelease :many
SELECT jira_id FROM release_jiras WHERE release_version = $1
`

func (q *Queries) GetJiraIDsByRelease(ctx context.Context, releaseVersion string) ([]string, error) {
	rows, err := q.db.Query(ctx, getJiraIDsByRelease, releaseVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jira_id string
		if err := rows.Scan(&jira_id); err != nil {
			return nil, err
		}
		items = append(items, jira_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkJiraToRelease = `-- name: LinkJiraToRelease :exec
INSERT INTO release_jiras (release_version, jira_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkJiraToReleaseParams struct {
	ReleaseVersion string `json:"release_version"`
	JiraID         string `json:"jira_id"`
}

func (q *Queries) LinkJiraToRelease(ctx context.Context, arg LinkJiraToReleaseParams) error {
	_, err := q.db.Exec(ctx, linkJiraToRelease, arg.ReleaseVersion, arg.JiraID)
	return err
}

const unlinkJirasFromRelease = `-- name: UnlinkJirasFromRelease :exec
DELETE FROM release_jiras WHERE release_version = $1
`

func (q *Queries) UnlinkJirasFromRelease(ctx context.Context, releaseVersion string) error {
	_, err := q.db.Exec(ctx, unlinkJirasFromRelease, releaseVersion)
	return err
}
